import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Box } from "@mui/material";
import { gql, useQuery } from "@apollo/client";
import client from "../services/apollo-client";
import { GET_REPOSITORIES } from "../services/graphql/queries";

export async function getStaticProps() {
  const { data } = await client.query({
    query: GET_REPOSITORIES,
    variables: {
      query: "releasy",
    },
  });

  return {
    props: {
      data,
    },
  };
}
export default function Home() {
  const { data } = useQuery(GET_REPOSITORIES, {
    variables: {
      query: "releasy",
    },
  });

  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box></Box>
    </div>
  );
}
