import Head from "next/head";

import { Box, FormControl, TextField } from "@mui/material";
import { GET_REPOSITORIES } from "../services/graphql/queries";
import theme from "../services/theme";
import { useState } from "react";
import DisplayData from "../components/DisplayData/DisplayData";
import Menu from "../components/Menu/Menu";
import SearchIcon from "@mui/icons-material/Search";

export default function Home() {
  const [section, setSection] = useState(GET_REPOSITORIES);
  const [query, setQuery] = useState("");

  return (
    <div>
      <Head>
        <title>GitHub GraphQL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          height: "100vh",
          p: 5,
          display: "flex",
          justifyContent: "center",
          backgroundColor: theme.palette.primary.dark,
        }}
      >
        <Menu section={section} setSection={setSection} />
        <Box sx={{ width: "70%" }}>
          <FormControl
            sx={{
              p: 1,
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <SearchIcon
              sx={{
                color: theme.palette.grey.white,
                position: "absolute",
                transform: "translateY(-50%)",
              }}
            />

            <TextField
              sx={{
                backgroundColor: theme.palette.grey.grey,
                borderRadius: "5px",
                width: "100%",
                borderColor: theme.palette.grey.grey80,
                "& .MuiOutlinedInput-root": {
                  "& fieldset": {
                    borderColor: theme.palette.grey.grey,
                  },
                  "&:hover fieldset": {
                    borderColor: theme.palette.grey.grey,
                  },
                  "&.Mui-focused fieldset": {
                    borderColor: theme.palette.grey.grey,
                  },
                },
                color: theme.palette.grey.grey,
              }}
              id="outlined-basic"
              variant="outlined"
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
            />
          </FormControl>
          <DisplayData query={query} section={section} />
        </Box>
      </Box>
    </div>
  );
}
