import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Box, ButtonGroup, Button } from "@mui/material";
import { gql, useQuery } from "@apollo/client";
import client from "../services/apollo-client";
import { GET_REPOSITORIES } from "../services/graphql/queries";
import theme from "../services/theme";
import { useState } from "react";

export async function getStaticProps() {
  const { data } = await client.query({
    query: GET_REPOSITORIES,
    variables: {
      query: "releasy",
    },
  });

  return {
    props: {
      data,
    },
  };
}
export default function Home() {
  const [type, setType] = useState("repositories");

  const { data } = useQuery(GET_REPOSITORIES, {
    variables: {
      query: "releasy",
    },
  });

  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          width: "100%",
          height: "100vh",
          display: "flex",
          backgroundColor: theme.palette.primary.dark,
        }}
      >
        <Box
          sx={{
            width: "70%",
            height: "90%",
            backgroundColor: theme.palette.grey.grey90,
            borderRadius: "10px",
            margin: "auto",
          }}
        >
          <Box
            sx={{
              display: "flex",
              "& > *": {
                m: 1,
              },
            }}
          >
            <ButtonGroup
              sx={{
                padding: 5,
                width: "25%",
                textAlign: "start",
                color: "white",
              }}
              orientation="vertical"
              aria-label="vertical outlined button group"
            >
              <Button
                onClick={() => {
                  setType("REPOSITORIES");
                }}
                key="one"
              >
                Repositories
              </Button>
              <Button key="two">Code</Button>
              <Button key="three">Commits</Button>
              <Button key="one">Issues</Button>
              <Button key="two">Discussion</Button>
              <Button key="three">Packages</Button>
              <Button key="one">MarketPlace</Button>
              <Button key="two">Wikis</Button>
              <Button key="three">Users</Button>
            </ButtonGroup>
          </Box>
        </Box>
      </Box>
    </div>
  );
}
